### ISSUE TITLE
which part in your code re-implemented DeepSnake with FCOS as the object detector?

### ISSUE THREAD

**Issue by cccccccccy** [lkevinzc/dance#1]
I have read your paper, and it mentioned you re-implemented DeepSnake with FCOSas the object detector for fair comparison. So
can you tell me which part re-implemented DeepSnake with FCOS in your code? Thanks !

**Comment by lkevinzc** [comment]
Hi! Thanks for your interest!

https://github.com/lkevinzc/dance/blob/master/core/modeling/edge_snake/snake_head.py#L617

Starting from here, it uses a snake module to first generate extreme points and then create the octagon, afterwards do mask regression.

**Comment by cccccccccy** [comment]
Hi! Thanks for your excellent work! I still have another question.  FCOS generates bbox_prediction with H*W*4 dimensions, and in my opinion we need to select right bboxes as the deformation's input. Is my understanding correct? And if it is correct, how to select right bboxes and which part of your code implements this work?
Thanks for your reply!

**Comment by lkevinzc** [comment]
@cccccccccy 
The NMS process should select those high quality object boxes for you. The deformation is based on those selected boxes.
Here is where the FCOS does NMS as post-processing: https://github.com/lkevinzc/dance/blob/57ffc777c52024c351293fe39ba217ae7f1fa24f/core/modeling/fcose/fcose_outputs.py#L528

**Comment by cccccccccy** [comment]
Hi! , One error occurred，when I used coco2017 dataset for training. The command is `python train_net.py --num-gpus 1 --config-file configs/Dance_R_50_3x.yaml`  And the error is `FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/edge_train2017'` Does this still require some preprocessing files for training？

**Comment by lkevinzc** [comment]
@cccccccccy Hi, yes. You need to use [this script](https://github.com/lkevinzc/dance/blob/master/datasets/prepare_edge_map.py) to prepare the training data first.
