### ISSUE TITLE
There have been a  problem when I used the   prepare_edge_map.py, it prompted that the corresponding picture is missing

### ISSUE THREAD

**Issue by Dyt5358** [lkevinzc/dance#11]
![3d4b91d40ea710ab4f0ce40e0e32a18](https://user-images.githubusercontent.com/74446581/128819460-ccd0e1a2-8b19-4827-b12d-f5d2288329ca.png)

Hi, so sorry to bother you,  i am a newbie so that my question may be very silly. 
I don't know why it indicates that the picture is missing, but the picture exists..Do you know how to solve the problem? Thank you.

**Comment by lkevinzc** [comment]
Hi @Dyt5358 , sorry for the late reply. Is the problem fixed?
