### ISSUE TITLE
About code on coco

### ISSUE THREAD

**Issue by Yinyf0804** [lkevinzc/dance#12]
Thanks for your great work. I have a question that why do you reproduce your code on detectron2 when training on coco, instead of directly using 'snake' code?  Since files of coco dataset (dataset and evaluation for coco) have already existed in 'snake' (though snake does not use them).

**Comment by lkevinzc** [comment]
Hi @Yinyf0804 , thanks for your attention.

Because I think the detector in 'snake' is not as good as FCOS implemented in detectron2, which cannot perform so well for challenging dataset like COCO.

**Comment by Yinyf0804** [comment]
Thanks for your reply!
