### ISSUE TITLE
How to get edge_map of SBD?

### ISSUE THREAD

**Issue by Zhang-Jing-Xuan** [lkevinzc/dance#16]
Hi, so sorry to bother you. Is there any code for the edge map generation from data of SBD? I only find coco and cityscapes in the datasets folder. Thanks.

**Comment by lkevinzc** [comment]
Hi @Zhang-Jing-Xuan , thanks for your interest! You may directly use the code for coco after preparing the sbd dataset in COCO format. I used that to generate the edge map for SBD dataset. 

If I remember correctly, this [link](https://github.com/zju3dv/snake/blob/master/INSTALL.md#sbd) provided by deepsnake codebase has a great dataset zip file. Maybe you could check and let me know if there is any issues. :)
