### ISSUE TITLE
您好，我看了下基于deepsnake的dance模型，在配置文件看来，好像不需要学习预测目标中心点的偏移量？

### ISSUE THREAD

**Issue by zylofor** [lkevinzc/dance#18]

**Comment by lkevinzc** [comment]
你好！不需要，预测的是contour上的采样点的偏移。

**Comment by zylofor** [comment]
> 



> 你好！不需要，预测的是contour上的采样点的偏移。

非常感谢您的回复，您的工作很有启发。但是仍然有些地方不明白，Loss部分需要计算中心点偏移量，是否意味着`ex_loss=self.ex_crit(output['ex_pred],out['i_gt_4py'])`这行代码需要注释？因为这两个值是从原snake初始化过来的，现在并没有这个键值。然而，这个如果注释了，该如何优化原来检测器的的中心点偏移损失？

**Comment by lkevinzc** [comment]
检测器是基于FCOS的，细节和loss设计等都在文章里（ https://arxiv.org/abs/1904.01355 ）。

总的来说就是第一阶段（检测）的loss加上第二阶段（deformation）的loss合成最后的loss，同时对整个网络做优化。
