### ISSUE TITLE
About the training usage and some missing files

### ISSUE THREAD

**Issue by HsiaX** [lkevinzc/dance#2]
Hi, so sorry to bother you, but where is the training usage? And I noticed that some necessary file were missing, such as: core/modeling/backbone/mobilenet.py & vovnet.py, the panopticapi package, where can I find them?

**Comment by lkevinzc** [comment]
@HsiaX Hi, thanks for your interest.

This is built on Detectron2, the training command is also similar to that. For example, `python train_net.py --num-gpus 2 --config-file configs/Dance_R_50_3x.yaml`.

I did not use mobilenet/vovnet in the final models; I just used them in some experiments during quite early stages.

The `panopticapi` can be found here: https://github.com/cocodataset/panopticapi.

**Comment by HsiaX** [comment]
> 
> 
> @HsiaX Hi, thanks for your interest.
> 
> This is built on Detectron2, the training command is also similar to that. For example, `python train_net.py --num-gpus 2 --config-file configs/Dance_R_50_3x.yaml`.
> 
> I did not use mobilenet/vovnet in the final models; I just used them in some experiments during quite early stages.
> 
> The `panopticapi` can be found here: https://github.com/cocodataset/panopticapi.



OK, I got it. Thanks so much for your reply!  :-)
By the way, now I have generated the edge file (use the Cityscapes from Deep Snake), but they seems almost black. Is this normal?

**Comment by HsiaX** [comment]
Unfortunately, now I meet the following error info during training:
![图片](https://user-images.githubusercontent.com/44256703/112116556-5f79d380-8bf5-11eb-918b-aceb2632a846.png)
Is it means that the edge_gt is empty? I got the edge file like this, what happened? (T_T)
![图片](https://user-images.githubusercontent.com/44256703/112117028-de6f0c00-8bf5-11eb-97b0-d8ff0903d2a5.png)

**Comment by lkevinzc** [comment]
Hi @HsiaX , the edge map should contain values 0/1, so nearly not visible by human eyes. If you load it into notebook and multiply by 255 and check, it should be correct.

From the log I guess it's something related to the dataloader. 

I mainly used this repo's code for COCO training, and did not encounter such issues. If you want to do experiments on cityscape, I have some codes based on DeepSnake repo and changed it into our method, maybe you want to take a look?

**Comment by HsiaX** [comment]
> 
> 
> Hi @HsiaX , the edge map should contain values 0/1, so nearly not visible by human eyes. If you load it into notebook and multiply by 255 and check, it should be correct.
> 
> From the log I guess it's something related to the dataloader.
> 
> I mainly used this repo's code for COCO training, and did not encounter such issues. If you want to do experiments on cityscape, I have some codes based on DeepSnake repo and changed it into our method, maybe you want to take a look?

Yes you're right, the edge map is correct. 
Oh if you can provide that, that's soooooo great !

And, I found that the error occurs because in training set, there are some images without objects, so the edge is empty. Maybe I need to think about how to modify the code to deal with it.

**Comment by lkevinzc** [comment]
> > Hi @HsiaX , the edge map should contain values 0/1, so nearly not visible by human eyes. If you load it into notebook and multiply by 255 and check, it should be correct.
> > From the log I guess it's something related to the dataloader.
> > I mainly used this repo's code for COCO training, and did not encounter such issues. If you want to do experiments on cityscape, I have some codes based on DeepSnake repo and changed it into our method, maybe you want to take a look?
> 
> Yes you're right, the edge map is correct.
> Oh if you can provide that, that's soooooo great !
> 
> And, I found that the error occurs because in training set, there are some images without objects, so the edge is empty. Maybe I need to think about how to modify the code to deal with it.

Yes, definitely need to align the image with its correct annotation for training. Can provide your email so that I can send the zipped code to you?

**Comment by HsiaX** [comment]
> 
> 
> > > Hi @HsiaX , the edge map should contain values 0/1, so nearly not visible by human eyes. If you load it into notebook and multiply by 255 and check, it should be correct.
> > > From the log I guess it's something related to the dataloader.
> > > I mainly used this repo's code for COCO training, and did not encounter such issues. If you want to do experiments on cityscape, I have some codes based on DeepSnake repo and changed it into our method, maybe you want to take a look?
> > 
> > 
> > Yes you're right, the edge map is correct.
> > Oh if you can provide that, that's soooooo great !
> > And, I found that the error occurs because in training set, there are some images without objects, so the edge is empty. Maybe I need to think about how to modify the code to deal with it.
> 
> Yes, definitely need to align the image with its correct annotation for training. Can provide your email so that I can send the zipped code to you?

OK，my email is: chenfei_xia@hust.edu.cn
Thank you!

**Comment by HsiaX** [comment]
Hi~ Sorry to bother you again. For these day's struggle, I wonder if there are some filter strategies during generating edge targets? When I was training, it would report that the edge_target is empty,then I filter the edge maps (some images has too small objects to generate edges, so I remove them from annos). But it doesn't work.

For example:
![图片](https://user-images.githubusercontent.com/44256703/112708877-cf3ad780-8eef-11eb-8e8f-b2b24f6e4b55.png)
It can be seen that the image has edges in initial edge map, but in snake_head.py, it report that the "init_ex_targets" is empty. So I want to know are there any  filter strategies in edge_target generating?

**Comment by lkevinzc** [comment]
Hi @HsiaX , there should be no filtering process inside `prepare_edge_map_cityscapes.py`, the code just extracts the segmentation annotation and draws the contours to get edge_map.

As you said, the training example has edge map, so the edge map annotation is correct; but you mentioned the error is  `init_ex_targets` is empty, I guess the problem may be your polygon annotation is not in clockwise/counter-clockwise order so that it cannot sample the target points?

BTW, if you are training on Cityscape, I would suggest you use the `snake` branch (same as the code I email you), which is based on DeepSnake codebase and the code is cleaner.  :)

Feel free to ask if you got further questions, or you can email me your wechat if you want and discuss there.
