### ISSUE TITLE
Config of model

### ISSUE THREAD

**Issue by Kurisu-para** [lkevinzc/dance#21]
Hi,

Thank you for your great work on Dance! I am trying to better understand this work so I want to train this model. I noticed that you have answered a issue about this, and I want to know if the config in https://github.com/lkevinzc/dance/blob/master/core/config/defaults.py is the same as the config you used in pre-trained model you provided? I noticed you set `_C.MODEL.SNAKE_HEAD.ATTENTION = False` and `_C.MODEL.SNAKE_HEAD.NEW_MATCHING = False`.

Sorry to bother you if I have misunderstood the model.

**Comment by lkevinzc** [comment]
`defaults.py` provides the default configurations, and will be overwritten by specific config files like this one: https://github.com/lkevinzc/dance/blob/master/configs/Dance_R_50_3x.yaml.

**Comment by Kurisu-para** [comment]
Thank you for your time and kindly reply!
