### ISSUE TITLE
Some questions about training strategies

### ISSUE THREAD

**Issue by cccccccccy** [lkevinzc/dance#4]
Hi, I have noticed that DeepSnake adopt the two-stage training strategies on cityscapes dataset , which train the detector alone firstly and then train the detector and snake branches simultaneously. And I also noticed that Dance are trained using SGD. So I want to know if Dance has adopted a two-stage training strategy, or directly trained end-to-end. 
Thanks for your reply!

**Comment by lkevinzc** [comment]
Hi @cccccccccy ! Thanks for the attention. No we did not use 2-stage training.

BTW, for cityscape training, we suggest the `snake` branch since it's developed based on the codebase of DeepSnake, and it can be compared more clearly.
