### ISSUE TITLE
Face an error when running author's code

### ISSUE THREAD

**Issue by Archer222arc** [lkevinzc/dance#5]
Traceback (most recent call last):
  File "train_net.py", line 14, in <module>
    import core.data  # noqa
  File "/public/home/archer/dance/core/__init__.py", line 1, in <module>
    from core import modeling
  File "/public/home/archer/dance/core/modeling/__init__.py", line 1, in <module>
    from .fcos import FCOS
  File "/public/home/archer/dance/core/modeling/fcos/__init__.py", line 1, in <module>
    from .fcos import FCOS
  File "/public/home/archer/dance/core/modeling/fcos/fcos.py", line 10, in <module>
    from core.layers import DFConv2d, IOULoss
  File "/public/home/archer/dance/core/layers/__init__.py", line 4, in <module>
    from .extreme_utils import _ext as extreme_utils
ImportError: cannot import name '_ext' from 'core.layers.extreme_utils' (/public/home/archer/dance/core/layers/extreme_utils/__init__.py)
And I find there's nothing in _init_.py

**Comment by lkevinzc** [comment]
Hi @Archer222arc , thanks for your interest.
To run, you need to first build and install the package, as mentioned in the README: 
- install cpp utils: `cd dance/core/layers/extreme_utils && export CUDA_HOME="/usr/local/cuda-10.1" && python setup.py build_ext --inplace`

**Comment by Archer222arc** [comment]
Thank you for help! The above problems is solved and I have another problem. Since the evaluation relies on "edge.json", I've tried using `prepare_edge_map.py` to generate the corresponding json file consisting of edges of `COCOval2017` but failed. More specifically, the `annotations_val2017.json`'s "annotation":[] information does not include "file_name". I'm a new to handle this kind of problem. Could you please give some help? Thank you.

**Comment by lkevinzc** [comment]
Hi @Archer222arc , actually, when you run `prepare_edge_map.py`, both training and evaluation data will be process (see this line of [code](https://github.com/lkevinzc/dance/blob/master/datasets/prepare_edge_map.py#L82). As long as you have the coco train and eval folders correctly, it should generate edge map data for both train and eval set.
