### ISSUE TITLE
Can I have a simple training on a graphics card？

### ISSUE THREAD

**Issue by David9591** [lkevinzc/dance#7]
First of all, thank you for your excellent work.I have successfully tested your model so far, but when I tried to train the model so that I could observe the flow of data, I ran into a problem: I only have one piece of 1080Ti(11G), and when I ran it, the video memory was exceeded. What parameters should I adjust if I want to train on a video card?Could you give me some advice?Thank you very much!

**Comment by lkevinzc** [comment]
@David9591 Hi there! Thanks and sorry for the late reply. If you have the out of memory error, you may try to use smaller backbone network, or you can reduce the input image resolution.
