### ISSUE TITLE
Config file (.yaml) of the basic DsnakeHead.

### ISSUE THREAD

**Issue by LiWentomng** [lkevinzc/dance#9]
Hi, thanks for your excellent codes. Now, I want to train the basic [dsnake_head](https://github.com/lkevinzc/dance/blob/master/core/modeling/dsnake_baseline/dsnake_head.py).  Would you like to provide the config(.yaml) file of this model？  Look forward to your reply!

**Comment by lkevinzc** [comment]
Hi @LiWentomng , thank you for your attention!
Please see the newly added file [here](https://github.com/lkevinzc/dance/blob/master/configs/Dsnake_R_50_1x.yaml).
